server:
  port:  8081
#  person:
#    lastName: zhangsan
#    age: 12
#    boss: false
#    birth: 2017/12/12
#    maps: {k1: v1,k2: 12}
#    lists:
#        - lisi
#        - zhaoliu
#    dog:
#         name: é»‘
#         age: 2

